---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: 
  - rm Gemfile.lock || true
  - gem update bundler
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.3.1
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
  - PUPPET_GEM_VERSION="~> 4.3.0"
  - PUPPET_GEM_VERSION="~> 4.4.0"
  - PUPPET_GEM_VERSION="~> 4.5.0"
  - PUPPET_GEM_VERSION="~> 4.6.0"
  - PUPPET_GEM_VERSION="~> 4.7.0"
  - PUPPET_GEM_VERSION="~> 4.8.0" FUTURE_PARSER=yes
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER=yes
